Update feedback.js
grapheo12/erp_feedback pull request #3
Opened 2021-04-06 18:25 UTC by harshitjain0510

On line 9 now, variable 'i' is starting from 3, so it's not working for more than 3 teachers. Change back 'i' to 1 and can add:-

if(x[i].getAttribute('name') == 'check'){continue;}

in loop before x[i].click()

It will work for any n number of teachers.

2021-04-07 10:56 UTC, grapheo12 commented
@harshitjain0510 Have you tested this yourself?
If yes I'll merge it right away.

2021-04-07 10:59 UTC, grapheo12 requested changes
Please do the needful

2021-04-07 10:59 UTC, grapheo12 commented on feedback.js
> +        if(x[i].getAttribute('name') == 'check'){continue;}
Would you care to format this part? This is just my OCD :sweat:

2021-04-07 11:29 UTC, harshitjain0510 commented
> @harshitjain0510 Have you tested this yourself?
> If yes I'll merge it right away.

Yes, tried and tested.

2021-04-08 05:54 UTC, thealphadollar approved these changes
LGTM. Tried and tested in times of need XD

2021-04-08 05:55 UTC, merged